; #FUNCTION# ====================================================================================================================
; Name ..........: CSV Maker Main GUI
; Description ...:
; Syntax ........:
; Parameters ....:
; Return values .:
; Author ........: ratakantez
; Modified ......: ratakantez (12th March 2022)
; Remarks .......: This file is part of MyBot, previously known as ClashGameBot. Copyright 2015-2022
;                  MyBot is distributed under the terms of the GNU GPL
; Related .......: MyBOT
; Link ..........:
; Example .......:
; ===============================================================================================================================
Func _GUICreateCSV($title, $width, $height, $left = -1, $top = -1, $style = -1, $exStyle = -1, $parent = 0)
	$GUI_CSV_in_function = GUICreate($title, $width, $height, $left, $top, $style, $exStyle, $parent)
	GUISetBkColor(0xFFFF99,$GUI_CSV_in_function)
	Local $key = String($GUI_CSV_in_function)
	Local $obj = $GUI_CSV_in_function
	$g_oGuiNotInMini.Add($key, $obj)
	GUISetIcon("csv.ico",$GUI_CSV_in_function)
	Return $GUI_CSV_in_function
 EndFunc   ;==>_GUICreate

Func GUI_CSVMAKER()
$h_hGUI_MakeCsv = _GUICreateCSV($Program_Name & " 2022 " & $Program_Version, 1026, 640, @DesktopWidth/2-1026/2, @DesktopHeight/2-640/2, $WS_BORDER, $WS_EX_CONTROLPARENT)
Local $x = 15
Local $y = 18
$MainPic = GUICtrlCreatePic(@ScriptDir & "\COCBot\CSVMAKER2022\USE\mainbackground.bmp", $x - 14, $y - 17, 845, 361)
GUICtrlSetState($MainPic, $GUI_DISABLE)
$MainGoldStoragePic = GUICtrlCreatePic("", $x, $y, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainGoldStoragePic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\GoldStorage.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainGoldStoragePic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\GoldStorage.png"))))
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Gold Storage")
$MainElixirStoragePic = GUICtrlCreatePic("", $x, $y + 55, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainElixirStoragePic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\ElixirStorage.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainElixirStoragePic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\ElixirStorage.png"))))
GUICtrlSetTip(-1, "Elixir Storage")
GUICtrlSetState(-1,$GUI_DISABLE)
$MainDarkElixirStoragePic = GUICtrlCreatePic("", $x, $y + 110, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainDarkElixirStoragePic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\DarkElixir.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainDarkElixirStoragePic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\DarkElixir.png"))))
GUICtrlSetTip(-1, "Dark Elixir Storage")
GUICtrlSetState(-1,$GUI_DISABLE)
$MainGoldCollectorPic = GUICtrlCreatePic("", $x, $y + 165, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainGoldCollectorPic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\Mine.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainGoldCollectorPic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\Mine.png"))))
GUICtrlSetTip(-1, "Mine")
GUICtrlSetState(-1,$GUI_DISABLE)
$MainElixirCollectorPic = GUICtrlCreatePic("", $x, $y + 220, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainElixirCollectorPic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\collector.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainElixirCollectorPic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\collector.png"))))
GUICtrlSetTip(-1, "Elixir Colector")
GUICtrlSetState(-1,$GUI_DISABLE)
$MainDarkElixirCollectorPic = GUICtrlCreatePic("", $x, $y + 275, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainDarkElixirCollectorPic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\Drill.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainDarkElixirCollectorPic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\Drill.png"))))
GUICtrlSetTip(-1, "Drill")
GUICtrlSetState(-1,$GUI_DISABLE)

$GoldStorageSlider = GUICtrlCreateSlider($x + 57, $y + 5, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($GoldStorageSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Gold Storage to exist in your main side.")
GUICtrlSetLimit($GoldStorageSlider, 20, 0)
$GoldStorageCheckBox = GUICtrlCreateCheckbox("Give Chance to Gold Storage", $x + 65, $y + 30, 175, 18)
GUICtrlSetOnEvent(-1,"GoldStorageCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Gold Storage to exist in your main side.")
$ElixirStorageSlider = GUICtrlCreateSlider($x + 57, $y + 60, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($ElixirStorageSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Elixir Storage to exist in your main side.")
GUICtrlSetLimit($ElixirStorageSlider, 20, 0)
$ElixirStorageCheckBox = GUICtrlCreateCheckbox("Give Chance to Elixir Storage", $x + 65, $y + 85, 175, 18)
GUICtrlSetOnEvent(-1,"ElixirStorageCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Elixir Storage to exist in your main side.")
$DarkElixirStorageSlider = GUICtrlCreateSlider($x + 57, $y + 115, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($DarkElixirStorageSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Dark Elixir Storage to exist in your main side.")
GUICtrlSetLimit($DarkElixirStorageSlider, 20, 0)
$DarkElixirStorageCheckBox = GUICtrlCreateCheckbox("Give Chance to Dark Elx. Storage", $x + 65, $y + 140, 175, 18)
GUICtrlSetOnEvent(-1,"DarkElixirStorageCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Dark Elixir Storage to exist in your main side.")
$GoldCollectorSlider = GUICtrlCreateSlider($x + 57, $y + 170, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($GoldCollectorSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Mine(s) to exist in your main side.")
GUICtrlSetLimit($GoldCollectorSlider, 20, 0)
$GoldCollectorCheckBox = GUICtrlCreateCheckbox("Give Chance to Mines", $x + 65, $y + 195, 175, 18)
GUICtrlSetOnEvent(-1,"GoldCollectorCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Mine(s) to exist in your main side.")
$ElixirCollectorSlider = GUICtrlCreateSlider($x + 57, $y + 225, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($ElixirCollectorSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Elixir Collector(s) to exist in your main side.")
GUICtrlSetLimit($ElixirCollectorSlider, 20, 0)
$ElixirCollectorCheckBox = GUICtrlCreateCheckbox("Give Chance to Elx. Collectors", $x + 65, $y + 250, 175, 18)
GUICtrlSetOnEvent(-1,"ElixirCollectorCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Elixir Collector(s) to exist in your main side.")
$DarkElixirCollectorSlider = GUICtrlCreateSlider($x + 57, $y + 280, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($DarkElixirCollectorSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Drill(s) to exist in your main side.")
GUICtrlSetLimit($DarkElixirCollectorSlider, 20, 0)
$DarkElixirCollectorCheckBox = GUICtrlCreateCheckbox("Give Chance to Drills", $x + 65, $y + 305, 175, 18)
GUICtrlSetOnEvent(-1,"DarkElixirCollectorCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Drill(s) to exist in your main side.")

$GoldStoragePoint = GUICtrlCreateInput("0", $x + 240, $y + 10, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your Gold Storage Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)
$ElixirStoragePoint = GUICtrlCreateInput("0", $x + 240, $y + 65, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your Elixir Storage Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)
$DarkElixirStoragePoint = GUICtrlCreateInput("0", $x + 240, $y + 120, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your Dark Elixir Storage Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)
$MinePoint = GUICtrlCreateInput("0", $x + 240, $y + 175, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your Mine Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)
$CollectorPoint = GUICtrlCreateInput("0", $x + 240, $y + 230, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your Elixir Collector Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)
$DrillPoint = GUICtrlCreateInput("0", $x + 240, $y + 285, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your Drill Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)

$x = 290

$MainTHPic = GUICtrlCreatePic("", $x, $y, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainTHPic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\TH.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainTHPic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\TH.png"))))
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Town Hall")
$MainInfernoTowerPic = GUICtrlCreatePic("", $x, $y + 55, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainInfernoTowerPic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\inferno.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainInfernoTowerPic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\inferno.png"))))
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Inferno Tower")
$MainEaglePic = GUICtrlCreatePic("", $x, $y + 110, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainEaglePic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\eagle.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainEaglePic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\eagle.png"))))
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Eagle Artillery")
$MainXbowPic = GUICtrlCreatePic("", $x, $y + 165, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainXbowPic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\xbow.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainXbowPic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\xbow.png"))))
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "X-Bow")
$MainWizzTowerPic = GUICtrlCreatePic("", $x, $y + 220, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainWizzTowerPic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\wizz.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainWizzTowerPic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\wizz.png"))))
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Wizzard Tower")
$MainAirDeffancePic = GUICtrlCreatePic("", $x, $y + 275, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainAirDeffancePic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\air.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainAirDeffancePic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\air.png"))))
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Air Deffance")

$THSlider = GUICtrlCreateSlider($x + 57, $y + 5, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($THSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Town Hall to exist in your main side.")
GUICtrlSetLimit($THSlider, 20, 0)
$THCheckBox = GUICtrlCreateCheckbox("Give Chance to Town Hall", $x + 65, $y + 30, 175, 18)
GUICtrlSetOnEvent(-1,"THCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Town Hall to exist in your main side.")
$InfernoTowerSlider = GUICtrlCreateSlider($x + 57, $y + 60, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($InfernoTowerSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Inferno Tower to exist in your main side.")
GUICtrlSetLimit($InfernoTowerSlider, 20, 0)
$InfernoTowerCheckBox = GUICtrlCreateCheckbox("Give Chance to Inferno Tower", $x + 65, $y + 85, 175, 18)
GUICtrlSetOnEvent(-1,"InfernoTowerCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Inferno Tower to exist in your main side.")
$EagleSlider = GUICtrlCreateSlider($x + 57, $y + 115, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($EagleSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Eagle Artillery Storage to exist in your main side.")
GUICtrlSetLimit($EagleSlider, 20, 0)
$EagleCheckBox = GUICtrlCreateCheckbox("Give Chance to Eagle Artillery", $x + 65, $y + 140, 175, 18)
GUICtrlSetOnEvent(-1,"EagleCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Eagle Artillery Storage to exist in your main side.")
$XbowSlider = GUICtrlCreateSlider($x + 57, $y + 170, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($XbowSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance X-Bow to exist in your main side.")
GUICtrlSetLimit($XbowSlider, 20, 0)
$XbowCheckBox = GUICtrlCreateCheckbox("Give Chance to X-Bow", $x + 65, $y + 195, 175, 18)
GUICtrlSetOnEvent(-1,"XbowCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance X-Bow to exist in your main side.")
$WizzTowerSlider = GUICtrlCreateSlider($x + 57, $y + 225, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($WizzTowerSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Wizzard Tower to exist in your main side.")
GUICtrlSetLimit($WizzTowerSlider, 20, 0)
$WizzTowerCheckBox = GUICtrlCreateCheckbox("Give Chance to Wizzard Tower", $x + 65, $y + 250, 175, 18)
GUICtrlSetOnEvent(-1,"WizzTowerCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Wizzard Tower to exist in your main side.")
$AirDeffanceSlider = GUICtrlCreateSlider($x + 57, $y + 280, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($AirDeffanceSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Air Deffance to exist in your main side.")
GUICtrlSetLimit($AirDeffanceSlider, 20, 0)
$AirDeffanceCheckBox = GUICtrlCreateCheckbox("Give Chance to Air Deffance", $x + 65, $y + 305, 175, 18)
GUICtrlSetOnEvent(-1,"AirDeffanceCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Air Deffance to exist in your main side.")

$THPoint = GUICtrlCreateInput("0", $x + 240, $y + 10, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your Town Hall Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)
$infernoPoint = GUICtrlCreateInput("0", $x + 240, $y + 65, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your Inferno Tower Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)
$eaglepoint = GUICtrlCreateInput("0", $x + 240, $y + 120, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your Eagle Artillery Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)
$XbowpointPoint = GUICtrlCreateInput("0", $x + 240, $y + 175, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your X-Bow Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)
$WTowerPoint = GUICtrlCreateInput("0", $x + 240, $y + 230, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your Wizzard Tower Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)
$airpoint = GUICtrlCreateInput("0", $x + 240, $y + 285, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your Air Deffance Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)

$x = 571

$MainScaterPic = GUICtrlCreatePic("", $x, $y, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainScaterPic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\scattershot.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainScaterPic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\scattershot.png"))))
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Scattershot")
$MainMortarPic = GUICtrlCreatePic("", $x, $y + 55, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainMortarPic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\Mortar.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainMortarPic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\Mortar.png"))))
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Mortar")
$MainAirSweeperPic = GUICtrlCreatePic("", $x, $y + 110, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($MainAirSweeperPic, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\airsweeper.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($MainAirSweeperPic,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\airsweeper.png"))))
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Air Sweeper")

$ScaterSlider = GUICtrlCreateSlider($x + 57, $y + 5, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($ScaterSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Scattershot to exist in your main side.")
GUICtrlSetLimit($ScaterSlider, 20, 0)
$ScaterCheckBox = GUICtrlCreateCheckbox("Give Chance to Scattershot", $x + 65, $y + 30, 175, 18)
GUICtrlSetOnEvent(-1,"ScaterCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Scattershot to exist in your main side.")
$MortarSlider = GUICtrlCreateSlider($x + 57, $y + 60, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($MortarSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Mortar to exist in your main side.")
GUICtrlSetLimit($MortarSlider, 20, 0)
$MortarCheckBox = GUICtrlCreateCheckbox("Give Chance to Mortar", $x + 65, $y + 85, 175, 18)
GUICtrlSetOnEvent(-1,"MortarCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Mortar to exist in your main side.")
$AirSweeperSlider = GUICtrlCreateSlider($x + 57, $y + 115, 180, 23)
GUICtrlSetOnEvent(-1,"SliderControlInSideGui")
GUICtrlSetBkColor($AirSweeperSlider, 0xFFFF99)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Air Sweeper to exist in your main side.")
GUICtrlSetLimit($AirSweeperSlider, 20, 0)
$AirSweeperCheckBox = GUICtrlCreateCheckbox("Give Chance to Air Sweeper", $x + 65, $y + 140, 175, 14)
GUICtrlSetOnEvent(-1,"AirSweeperCheckBox")
GUICtrlSetTip(-1, "If you scrool the slider to right, " & @CRLF & "Bot give more chance Air Sweeper to exist in your main side.")

$ScatterShotPoint = GUICtrlCreateInput("0", $x + 240, $y + 10, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your Scattershot Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)
$MortarPoint = GUICtrlCreateInput("0", $x + 240, $y + 65, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your Mortar Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)
$AirSweeperpoint = GUICtrlCreateInput("0", $x + 240, $y + 120, 25, 23, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1,$GUI_HIDE)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Set Your Air Sweeper Point to Choose Main Attack Side")
GUICtrlSetLimit(-1, 2)
$y = $y + 20
$grpOtherSideOption = GUICtrlCreateGroup("", 1, 1, 1, 1) ;Radio Side Group
GUICtrlSetState(-1,$GUI_HIDE)
$MainLeftFrontPic = GUICtrlCreatePic(@ScriptDir & "\COCBot\CSVMAKER2022\USE\frontleft.bmp", $x + 10, $y + 170, 65, 65)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Choose Atack Side as Front Left Side")
$LeftFrontRadio =  GUICtrlCreateRadio("", $x + 62, $y + 228, 12, 12)
GUICtrlSetOnEvent(-1,"ForcedSideRadio")
GUICtrlSetTip(-1, "Choose Atack Side as Front Left Side")
GUICtrlSetBkColor(-1, 0xFFFF99)
$MainLeftBottomPic = GUICtrlCreatePic(@ScriptDir & "\COCBot\CSVMAKER2022\USE\bottomleft.bmp", $x + 100, $y + 170, 65, 65)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Choose Atack Side as Bottom Left Side")
$LeftBottomRadio =  GUICtrlCreateRadio("", $x + 154, $y + 228, 12, 12)
GUICtrlSetOnEvent(-1,"ForcedSideRadio")
GUICtrlSetTip(-1, "Choose Atack Side as Bottom Left Side")
GUICtrlSetBkColor(-1, 0xFFFF99)
$MainRightBottomPic = GUICtrlCreatePic(@ScriptDir & "\COCBot\CSVMAKER2022\USE\bottomright.bmp", $x + 190, $y + 170, 65, 65)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Choose Atack Side as Bottom Right Side")
$RightBottomRadio =  GUICtrlCreateRadio("", $x + 244, $y + 228, 12, 12)
GUICtrlSetOnEvent(-1,"ForcedSideRadio")
GUICtrlSetTip(-1, "Choose Atack Side as Bottom Right Side")
GUICtrlSetBkColor(-1, 0xFFFF99)
$MainRightFrontPic = GUICtrlCreatePic(@ScriptDir & "\COCBot\CSVMAKER2022\USE\frontright.bmp", $x + 55, $y + 245, 65, 65)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Choose Atack Side as Front Left Side")
$RightFrontRadio =  GUICtrlCreateRadio("", $x + 107, $y + 302, 12, 12)
GUICtrlSetOnEvent(-1,"ForcedSideRadio")
GUICtrlSetTip(-1, "Choose Atack Side as Bottom Right Side")
GUICtrlSetBkColor(-1, 0xFFFF99)
$MainRandomPic = GUICtrlCreatePic(@ScriptDir & "\COCBot\CSVMAKER2022\USE\random.bmp", $x + 145, $y + 245, 65, 65)
GUICtrlSetState(-1,$GUI_DISABLE)
GUICtrlSetTip(-1, "Choose Atack Side as Random Side")
$RandomRadio =  GUICtrlCreateRadio("", $x + 199, $y + 303, 12, 12)
GUICtrlSetOnEvent(-1,"ForcedSideRadio")
GUICtrlSetTip(-1, "Choose Atack Side as Random Side")
GUICtrlSetBkColor(-1, 0xFFFF99)
GUICtrlCreateGroup("", -99, -99, 1, 1)

$x = 15
$y = 18
$grpExpertOnOff = GUICtrlCreateGroup("Expert Side", 100000000, 1, 1, 1) ;Expert Group
GUICtrlSetState(-1,$GUI_HIDE)
$OnExpertRadio = GUICtrlCreateRadio("On Expert Option", $x + 570, $y + 168 ,120 ,13)
GUICtrlSetOnEvent(-1,"ExpertONorOFF")
GUICtrlSetTip(-1, "This shows point box for building to determine main side and disable slider" & @CRLF & "(This option is for persons who now coding about CSV File)")
GUICtrlSetFont(-1, 9, 800, 4, "MS Sans Serif")
GUICtrlSetColor(-1, 0x800000)
$OffExpertRadio = GUICtrlCreateRadio("Off Expert Option", $x + 695, $y + 168 ,120 ,13)
GUICtrlSetOnEvent(-1,"ExpertONorOFF")
GUICtrlSetState(-1,$GUI_CHECKED)
GUICtrlSetFont(-1, 9, 800, 4, "MS Sans Serif")
GUICtrlSetColor(-1, 0x800000)
GUICtrlCreateGroup("", -99, -99, 1, 1)

$x = 15
$y = 365
$Note = GUICtrlCreateEdit("", $x, $y - 2, 160, 145, BitOR($ES_AUTOVSCROLL, $ES_AUTOHSCROLL, $ES_WANTRETURN))
GUICtrlSetData(-1, "Author: " & @UserName & " - ver. x.x" & @CRLF & _NowDate() & @CRLF & @CRLF & "Troops: " & @CRLF & "Spells: " & @CRLF & "CC: " & @CRLF & "Info..... ")
GUICtrlSetColor(-1, 0x800000)
GUICtrlSetBkColor(-1, 0xD7E4F2)
GUICtrlSetTip(-1, "You can write a description for your CSV File" & @CRLF & "Such as Author Name,Army and CC info.. ")

$OpenTrain = GUICtrlCreateButton("", $x + 170, $y - 2, 135, 146, BitOR($BS_CENTER, $BS_BITMAP, $WS_BORDER))
GUICtrlSetOnEvent(-1,"ShowTrainMenu")
GUICtrlSetCursor (-1, 0)
GUICtrlSetImage($OpenTrain, @ScriptDir & "\COCBot\CSVMAKER2022\USE\think_barbarian.bmp", 0)
$CloseTrain = GUICtrlCreateButton("", $x + 170, $y - 2, 135, 146, BitOR($BS_CENTER, $BS_BITMAP, $WS_BORDER))
GUICtrlSetCursor (-1, 0)
GUICtrlSetState(-1, $GUI_HIDE)
GUICtrlSetOnEvent(-1,"SaveandExitTrainMenu")
GUICtrlSetImage($CloseTrain, @ScriptDir & "\COCBot\CSVMAKER2022\USE\closetraining.bmp", 0)
$MainInfoPic = GUICtrlCreatePic(@ScriptDir & "\COCBot\CSVMAKER2022\USE\maininfo.bmp", $x + 313, $y - 3, 517, 149)
GUICtrlSetState(-1,$GUI_DISABLE)
$Tick = GUICtrlCreatePic("", $x, $y + 1100000000, 50, 50)
_GDIPlus_Startup()
GUICtrlSendMsg($Tick, 0x0172, 0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(@ScriptDir & "\COCBot\CSVMAKER2022\USE\check.png"))
_WinAPI_DeleteObject(GUICtrlSendMsg($Tick,0x0172,0, _GDIPlus_BitmapCreateHBITMAPFromBitmap(_GDIPlus_ImageLoadFromFile(@ScriptDir & "\COCBot\CSVMAKER2022\USE\check.png"))))
GUICtrlSetState(-1,$GUI_DISABLE)
TrainGuiINMainGui() ; All Train Menu GUI

$lblFile = GUICtrlCreateLabel("File : ", $x, $y + 151, 35, -1)
GUICtrlSetFont(-1, 8, 800, 0, "Georgia")
GUICtrlSetColor(-1, 0x000080)
$FileInput = GUICtrlCreateInput("NoName_", $x + 39, $y + 148, 100, 23)
GUICtrlSetTip(-1, "You can write a specific name for your CSV File")

$Start = GUICtrlCreateButton("Start", $x, $y + 175, 139, 27)
GUICtrlSetFont(-1, 11, 800, 0, "Georgia")
GUICtrlSetColor(-1, 0x000080)
GUICtrlSetBkColor(-1, 0x008080)
GUICtrlSetOnEvent(-1,"StartButton")
$Exit = GUICtrlCreateButton("", $x, $y + 205 , 138, 41, BitOR($BS_CENTER, $BS_BITMAP, $WS_BORDER))
GUICtrlSetImage($Exit, @ScriptDir & "\COCBot\CSVMAKER2022\USE\exit.bmp", 0)
GUICtrlSetOnEvent(-1,"CloseCSVMakerGUI")

$LOG = _GUICtrlRichEdit_Create($h_hGUI_MakeCsv, "CSV WRITING IS STARTING" & @CRLF, 156, 513, 620, 100, BitOR($ES_MULTILINE, $ES_READONLY, $WS_VSCROLL, $WS_HSCROLL, $ES_UPPERCASE, $ES_AUTOHSCROLL, $ES_AUTOVSCROLL, $ES_NUMBER, 0x200), $WS_EX_STATICEDGE)

AfterStartGui ()

$GetHis = InetRead("https://raw.githubusercontent.com/ratakantez/UpdateCsvMaker_English/master/history.txt")
If @error Or $GetHis = "" Then Return
$GetHis = BinaryToString($GetHis)
$LabelHis = GUICtrlCreateLabel($GetHis, 852, 5, 165, 650,BitOR($WS_VISIBLE, $ES_AUTOVSCROLL, $SS_LEFT))
GUICtrlSetFont(-1, 6.5, $FW_BOLD, Default, "Arial", $CLEARTYPE_QUALITY)


EndFunc ; Main Gui