; #FUNCTION# ====================================================================================================================
; Name ..........: CSV Maker MultiDrop GUI for Side _D
; Description ...:
; Syntax ........:
; Parameters ....:
; Return values .:
; Author ........: ratakantez
; Modified ......: ratakantez (12th March 2022)
; Remarks .......: This file is part of MyBot, previously known as ClashGameBot. Copyright 2015-2022
;                  MyBot is distributed under the terms of the GNU GPL
; Related .......: MyBOT
; Link ..........:
; Example .......:
; ===============================================================================================================================

Func _GUICreateMultiDropforD($title, $width, $height, $left = -1, $top = -1, $style = -1, $exStyle = -1, $parent = 0)
   $GUI_MultiDropforD_in_function = GUICreate($title, $width, $height, $left, $top, $style, $exStyle, $parent)
   GUISetBkColor(0xFFFF99,$GUI_MultiDropforD_in_function)
   Local $key = String($GUI_MultiDropforD_in_function)
   Local $obj = $GUI_MultiDropforD_in_function
   $g_oGuiNotInMini.Add($key, $obj)
   GUISetIcon("csv.ico")
   Return $GUI_MultiDropforD_in_function
 EndFunc   ;==>_GUICreateMultiDropforD

 Func GUI_MultiDropforD()

;~ Left Part of Gui
   $h_hGUI_MakeMultiDropforD = _GUICreateMultiDropforD("Multi Drop For Part D", 660, 555, @DesktopWidth/2-660/2, @DesktopHeight/2-555/2, $WS_BORDER, $WS_EX_CONTROLPARENT)
   Local $x, $y
   $x = 15
   $y = 20
   $GroupForRandomPointforDShow = GUICtrlCreateGroup("Multi Mixed Points in Order", $x - 5, $y, 390, 470)
   DllCall("UxTheme.dll", "int", "SetWindowTheme", "hwnd", GUICtrlGetHandle($GroupForRandomPointforDShow), "wstr", 0, "wstr", 0)
   GUICtrlSetFont(-1, 9,$FW_BOLD,Default,"arial",$CLEARTYPE_QUALITY)
   GUICtrlSetColor(-1,0x808000)
   GUICtrlCreateGroup("", -99, -99, 1, 1)
   $x = 15
   $y = 40
   $GroupForRandomPointforD = GUICtrlCreateGroup("", $x + 10000000000, $y, 393, 393)
   $RadioForRandomforD = GUICtrlCreateRadio("", $x + 5, $y + 1 , 17, 17)
   GUICtrlSetTip(-1, "You can add mixed point up to ten quantity in order and for your CSV File")
   GUICtrlSetOnEvent($RadioForRandomforD,"ChooseMixedGuiforD")
   GUICtrlSetState(-1,$GUI_CHECKED)
   $RadioForLineforD= GUICtrlCreateRadio("", $x + 410, $y + 1 , 17, 17)
   GUICtrlSetTip(-1, "You can drop straightly limited quantity troop in order for your CSV File")
   GUICtrlSetOnEvent($RadioForLineforD,"ChooseLineGuiforD")
   $LblRandom1forD = GUICtrlCreateLabel("Let bot drop my " & $LOGName & "(s)", $x + 25, $y + 3, 300, 20)
   $LblRandom2forD = GUICtrlCreateLabel("in order...", $x + 20, $y + 23, 70, 20)
   $y = $y + 15
   $x = $x + 1
   $Lbl1forD = GUICtrlCreateLabel("1st Point is : ", $x, $y + 30, 65, 20)
   GUICtrlSetTip(-1, "Choose your 1st point to drop")
   $Lbl2forD = GUICtrlCreateLabel("2nd Point is : ", $x, $y + 70, 65, 20)
   GUICtrlSetTip(-1, "Choose your 2nd point to drop")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl3forD = GUICtrlCreateLabel("3rd Point is : ", $x, $y + 110, 65, 20)
   GUICtrlSetTip(-1, "Choose your 3rd point to drop")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl4forD = GUICtrlCreateLabel("4th Point is : ", $x, $y + 150, 65, 20)
   GUICtrlSetTip(-1, "Choose your 4th point to drop")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl5forD = GUICtrlCreateLabel("5th Point is : ", $x, $y + 190, 65, 20)
   GUICtrlSetTip(-1, "Choose your 5th point to drop")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl6forD = GUICtrlCreateLabel("6th Point is : ", $x, $y + 230, 65, 20)
   GUICtrlSetTip(-1, "Choose your 6th point to drop")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl7forD = GUICtrlCreateLabel("7th Point is : ", $x, $y + 270, 65, 20)
   GUICtrlSetTip(-1, "Choose your 7th point to drop")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl8forD = GUICtrlCreateLabel("8th Point is : ", $x, $y + 310, 65, 20)
   GUICtrlSetTip(-1, "Choose your 8th point to drop")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl9forD = GUICtrlCreateLabel("9th Point is : ", $x, $y + 350, 65, 20)
   GUICtrlSetTip(-1, "Choose your 9th point to drop")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl10forD = GUICtrlCreateLabel("10th Point is : ", $x, $y + 390 , 65, 20)
   GUICtrlSetTip(-1, "Choose your 10th point to drop")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $y = $y + 20
   $Lbl11forD = GUICtrlCreateLabel(" then sleep for next, between : ", $x, $y + 30, 150, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl12forD = GUICtrlCreateLabel(" then sleep for next, between : ", $x, $y + 70, 150, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl13forD = GUICtrlCreateLabel(" then sleep for next, between : ", $x, $y + 110, 150, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl14forD = GUICtrlCreateLabel(" then sleep for next, between : ", $x, $y + 150, 150, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl15forD = GUICtrlCreateLabel(" then sleep for next, between : ", $x, $y + 190, 150, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl16forD = GUICtrlCreateLabel(" then sleep for next, between : ", $x, $y + 230, 150, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl17forD = GUICtrlCreateLabel(" then sleep for next, between : ", $x, $y + 270, 150, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl18forD = GUICtrlCreateLabel(" then sleep for next, between : ", $x, $y + 310, 150, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl19forD = GUICtrlCreateLabel(" then sleep for next, between : ", $x, $y + 350, 150, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl20forD = GUICtrlCreateLabel(" then sleep for next, between : ", $x, $y + 390, 150, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $x = $x + 155
   $1stPointLowerSleepforD = GUICtrlCreateInput("50", $x, $y + 30, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $2ndPointLowerSleepforD = GUICtrlCreateInput("50", $x, $y + 70, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $3rdPointLowerSleepforD = GUICtrlCreateInput("50", $x, $y + 110, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $4thPointLowerSleepforD = GUICtrlCreateInput("50", $x, $y + 150, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $5thPointLowerSleepforD = GUICtrlCreateInput("50", $x, $y + 190, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $6thPointLowerSleepforD = GUICtrlCreateInput("50", $x, $y + 230, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $7thPointLowerSleepforD = GUICtrlCreateInput("50", $x, $y + 270, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $8thPointLowerSleepforD = GUICtrlCreateInput("50", $x, $y + 310, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $9thPointLowerSleepforD = GUICtrlCreateInput("50", $x, $y + 350, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $10thPointLowerSleepforD = GUICtrlCreateInput("50", $x, $y + 390, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $x = $x + 45
   $Lbl21forD = GUICtrlCreateLabel("-", $x, $y + 30, 5, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl22forD = GUICtrlCreateLabel("-", $x, $y + 70, 5, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl23forD = GUICtrlCreateLabel("-", $x, $y + 110, 5, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl24forD = GUICtrlCreateLabel("-", $x, $y + 150, 5, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl25forD = GUICtrlCreateLabel("-", $x, $y + 190, 5, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl26forD = GUICtrlCreateLabel("-", $x, $y + 230, 5, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   $Lbl27forD = GUICtrlCreateLabel("-", $x, $y + 270, 5, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl28forD = GUICtrlCreateLabel("-", $x, $y + 310, 5, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl29forD = GUICtrlCreateLabel("-", $x, $y + 350, 5, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl30forD = GUICtrlCreateLabel("-", $x, $y + 390, 5, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $x = $x + 10
   $1stPointUpperSleepforD = GUICtrlCreateInput("70", $x, $y + 30, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $2ndPointUpperSleepforD = GUICtrlCreateInput("70", $x, $y + 70, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $3rdPointUpperSleepforD = GUICtrlCreateInput("70", $x, $y + 110, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $4thPointUpperSleepforD = GUICtrlCreateInput("70", $x, $y + 150, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $5thPointUpperSleepforD = GUICtrlCreateInput("70", $x, $y + 190, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $6thPointUpperSleepforD = GUICtrlCreateInput("70", $x, $y + 230, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $7thPointUpperSleepforD = GUICtrlCreateInput("70", $x, $y + 270, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $8thPointUpperSleepforD = GUICtrlCreateInput("70", $x, $y + 310, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $9thPointUpperSleepforD = GUICtrlCreateInput("70", $x, $y + 350, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $10thPointUpperSleepforD = GUICtrlCreateInput("70", $x, $y + 390, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $x = $x + 45
   $Lbl31forD = GUICtrlCreateLabel("ms. (1000ms. = 1 sec.)", $x, $y + 30, 115, 17)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl32forD = GUICtrlCreateLabel("ms. (1000ms. = 1 sec.)", $x, $y + 70, 115, 17)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl33forD = GUICtrlCreateLabel("ms. (1000ms. = 1 sec.)", $x, $y + 110, 115, 17)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl34forD = GUICtrlCreateLabel("ms. (1000ms. = 1 sec.)", $x, $y + 150, 115, 17)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl35forD = GUICtrlCreateLabel("ms. (1000ms. = 1 sec.)", $x, $y + 190, 115, 17)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl36forD = GUICtrlCreateLabel("ms. (1000ms. = 1 sec.)", $x, $y + 230, 115, 17)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl37forD = GUICtrlCreateLabel("ms. (1000ms. = 1 sec.)", $x, $y + 270, 115, 17)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl38forD = GUICtrlCreateLabel("ms. (1000ms. = 1 sec.)", $x, $y + 310, 115, 17)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl39forD = GUICtrlCreateLabel("ms. (1000ms. = 1 sec.)", $x, $y + 350, 115, 17)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $Lbl40forD = GUICtrlCreateLabel("ms. (1000ms. = 1 sec.)", $x, $y + 390, 115, 17)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $x = 80
   $ComboMultiDrop1stPointforD = GUICtrlCreateCombo("", $x, $y + 8, 70, 17, $CBS_DROPDOWNLIST)
   GUICtrlSetTip(-1, "Choose your 1st point to drop")
   GUICtrlSetOnEvent($ComboMultiDrop1stPointforD,"CheckComboMultiDrop1stPointforD")
   GUICtrlSetFont(-1, 7, $FW_BOLD, Default, "Arial", $CLEARTYPE_QUALITY)
   GUICtrlSetData(-1, "Don't Use|Point 1|Point 2|Point 3|Point 4|Point 5|Point 6|Point 7|Point 8|Point 9|Point 10|","Don't Use")
   $ComboMultiDrop2ndPointforD = GUICtrlCreateCombo("", $x, $y + 48, 70, 17, $CBS_DROPDOWNLIST)
   GUICtrlSetTip(-1, "Choose your 2nd point to drop")
   GUICtrlSetOnEvent($ComboMultiDrop2ndPointforD,"CheckComboMultiDrop2ndPointforD")
   GUICtrlSetState(-1,$GUI_DISABLE)
   GUICtrlSetFont(-1, 7, $FW_BOLD, Default, "Arial", $CLEARTYPE_QUALITY)
   GUICtrlSetData(-1, "Don't Use|Point 1|Point 2|Point 3|Point 4|Point 5|Point 6|Point 7|Point 8|Point 9|Point 10|","Don't Use")
   $ComboMultiDrop3rdPointforD = GUICtrlCreateCombo("", $x, $y + 88, 70, 17, $CBS_DROPDOWNLIST)
   GUICtrlSetTip(-1, "Choose your 3rd point to drop")
   GUICtrlSetOnEvent($ComboMultiDrop3rdPointforD,"CheckComboMultiDrop3rdPointforD")
   GUICtrlSetState(-1,$GUI_DISABLE)
   GUICtrlSetFont(-1, 7, $FW_BOLD, Default, "Arial", $CLEARTYPE_QUALITY)
   GUICtrlSetData(-1, "Don't Use|Point 1|Point 2|Point 3|Point 4|Point 5|Point 6|Point 7|Point 8|Point 9|Point 10|","Don't Use")
   $ComboMultiDrop4thPointforD = GUICtrlCreateCombo("", $x, $y + 128, 70, 17, $CBS_DROPDOWNLIST)
   GUICtrlSetTip(-1, "Choose your 4th point to drop")
   GUICtrlSetOnEvent($ComboMultiDrop4thPointforD,"CheckComboMultiDrop4thPointforD")
   GUICtrlSetState(-1,$GUI_DISABLE)
   GUICtrlSetFont(-1, 7, $FW_BOLD, Default, "Arial", $CLEARTYPE_QUALITY)
   GUICtrlSetData(-1, "Don't Use|Point 1|Point 2|Point 3|Point 4|Point 5|Point 6|Point 7|Point 8|Point 9|Point 10|","Don't Use")
   $ComboMultiDrop5thPointforD = GUICtrlCreateCombo("", $x, $y + 168, 70, 17, $CBS_DROPDOWNLIST)
   GUICtrlSetTip(-1, "Choose your 5th point to drop")
   GUICtrlSetOnEvent($ComboMultiDrop5thPointforD,"CheckComboMultiDrop5thPointforD")
   GUICtrlSetState(-1,$GUI_DISABLE)
   GUICtrlSetFont(-1, 7, $FW_BOLD, Default, "Arial", $CLEARTYPE_QUALITY)
   GUICtrlSetData(-1, "Don't Use|Point 1|Point 2|Point 3|Point 4|Point 5|Point 6|Point 7|Point 8|Point 9|Point 10|","Don't Use")
   $ComboMultiDrop6thPointforD = GUICtrlCreateCombo("", $x, $y + 208, 70, 17, $CBS_DROPDOWNLIST)
   GUICtrlSetTip(-1, "Choose your 6th point to drop")
   GUICtrlSetOnEvent($ComboMultiDrop6thPointforD,"CheckComboMultiDrop6thPointforD")
   GUICtrlSetState(-1,$GUI_DISABLE)
   GUICtrlSetFont(-1, 7, $FW_BOLD, Default, "Arial", $CLEARTYPE_QUALITY)
   GUICtrlSetData(-1, "Don't Use|Point 1|Point 2|Point 3|Point 4|Point 5|Point 6|Point 7|Point 8|Point 9|Point 10|","Don't Use")
   $ComboMultiDrop7thPointforD = GUICtrlCreateCombo("", $x, $y + 248, 70, 17, $CBS_DROPDOWNLIST)
   GUICtrlSetTip(-1, "Choose your 7th point to drop")
   GUICtrlSetOnEvent($ComboMultiDrop7thPointforD,"CheckComboMultiDrop7thPointforD")
   GUICtrlSetState(-1,$GUI_DISABLE)
   GUICtrlSetFont(-1, 7, $FW_BOLD, Default, "Arial", $CLEARTYPE_QUALITY)
   GUICtrlSetData(-1, "Don't Use|Point 1|Point 2|Point 3|Point 4|Point 5|Point 6|Point 7|Point 8|Point 9|Point 10|","Don't Use")
   $ComboMultiDrop8thPointforD = GUICtrlCreateCombo("", $x, $y + 288, 70, 17, $CBS_DROPDOWNLIST)
   GUICtrlSetTip(-1, "Choose your 8th point to drop")
   GUICtrlSetOnEvent($ComboMultiDrop8thPointforD,"CheckComboMultiDrop8thPointforD")
   GUICtrlSetState(-1,$GUI_DISABLE)
   GUICtrlSetFont(-1, 7, $FW_BOLD, Default, "Arial", $CLEARTYPE_QUALITY)
   GUICtrlSetData(-1, "Don't Use|Point 1|Point 2|Point 3|Point 4|Point 5|Point 6|Point 7|Point 8|Point 9|Point 10|","Don't Use")
   $ComboMultiDrop9thPointforD = GUICtrlCreateCombo("", $x, $y + 328, 70, 17, $CBS_DROPDOWNLIST)
   GUICtrlSetTip(-1, "Choose your 9th point to drop")
   GUICtrlSetOnEvent($ComboMultiDrop9thPointforD,"CheckComboMultiDrop9thPointforD")
   GUICtrlSetState(-1,$GUI_DISABLE)
   GUICtrlSetFont(-1, 7, $FW_BOLD, Default, "Arial", $CLEARTYPE_QUALITY)
   GUICtrlSetData(-1, "Don't Use|Point 1|Point 2|Point 3|Point 4|Point 5|Point 6|Point 7|Point 8|Point 9|Point 10|","Don't Use")
   $ComboMultiDrop10thPointforD = GUICtrlCreateCombo("", $x, $y + 368, 70, 17, $CBS_DROPDOWNLIST)
   GUICtrlSetTip(-1, "Choose your 10th point to drop")
   GUICtrlSetOnEvent($ComboMultiDrop10thPointforD,"CheckComboMultiDrop10thPointforD")
   GUICtrlSetState(-1,$GUI_DISABLE)
   GUICtrlSetFont(-1, 7, $FW_BOLD, Default, "Arial", $CLEARTYPE_QUALITY)
   GUICtrlSetData(-1, "Don't Use|Point 1|Point 2|Point 3|Point 4|Point 5|Point 6|Point 7|Point 8|Point 9|Point 10|","Don't Use")

;~ Right Part of GUI
   $x = 420
   $y = 20
   $GroupforCenterCornerforDShow= GUICtrlCreateGroup("Multi Line Points in Order", $x - 5 , $y, 230, 170)
   DllCall("UxTheme.dll", "int", "SetWindowTheme", "hwnd", GUICtrlGetHandle($GroupforCenterCornerforDShow), "wstr", 0, "wstr", 0)
   GUICtrlSetFont(-1, 9,$FW_BOLD,Default,"arial",$CLEARTYPE_QUALITY)
   GUICtrlSetColor(-1,0x808000)
   GUICtrlCreateGroup("", -99, -99, 1, 1)
   $y = 40
   $PicforLinePointforD = GUICtrlCreatePic(@ScriptDir & "\COCBot\CSVMAKER2022\USE\multilineforD.bmp", $x + 35 , $y + 160, 134, 119,$WS_BORDER)
   $PicforLineDoublePointforD = GUICtrlCreatePic(@ScriptDir & "\COCBot\CSVMAKER2022\USE\multidoublelineforD.bmp", $x - 5 , $y + 160, 230, 119,$WS_BORDER)
   GUICtrlSetState(-1,$GUI_HIDE)
   $DoubleMultiDropforD = GUICtrlCreateCheckbox("", $x + 20, $y + 285, 18, 18)
   GUICtrlSetOnEvent($DoubleMultiDropforD,"CheckboxDoubleforD")
   $lblDoubleMultiDropforD = GUICtrlCreateLabel("Drop troop(s) from Side 'C' at the same time with the same settings.", $x + 41, $y + 285, 125, 42)
   GUICtrlSetState(-1,$GUI_DISABLE)
   $LblLine1forD = GUICtrlCreateLabel("Let bot drop my ", $x + 25, $y + 3, 80, 17)
   GUICtrlSetState(-1,$GUI_DISABLE)
   $ArmySizeinLineforD = GUICtrlCreateInput("", $x + 102, $y, 25, 20, $ES_NUMBER)
   GUICtrlSetTip(-1, "Enter your limit of troop quantity")
   GUICtrlSetLimit($ArmySizeinLineforD,3)
   GUICtrlSetState(-1,$GUI_DISABLE)
   $LblLine2forD = GUICtrlCreateLabel($LOGName & "(s)", $x + 132, $y + 3, 120, 17)
   GUICtrlSetState(-1,$GUI_DISABLE)
   $y = $y + 25
   $LblLine3forD = GUICtrlCreateLabel("in order between point ", $x + 20, $y, 115, 17)
   GUICtrlSetState(-1,$GUI_DISABLE)
   $InputLineBeginingforD = GUICtrlCreateInput("", $x + 132, $y - 3, 25, 21, $ES_NUMBER)
   GUICtrlSetTip(-1, "Enter your interval of Point that your troops are droped ")
   GUICtrlSetLimit($InputLineBeginingforD,2)
   GUICtrlSetState(-1,$GUI_DISABLE)
   $LblLine4forD = GUICtrlCreateLabel("and", $x + 163, $y, 22, 17)
   GUICtrlSetState(-1,$GUI_DISABLE)
   $InputLineEndingforD = GUICtrlCreateInput("", $x + 186, $y - 3, 25, 21, $ES_NUMBER)
   GUICtrlSetTip(-1, "Enter your interval of Point that your troops are droped ")
   GUICtrlSetLimit($InputLineEndingforD,2)
   GUICtrlSetState(-1,$GUI_DISABLE)
   $y = $y + 29
   $LblLine5forD = GUICtrlCreateLabel("from", $x + 20, $y, 24, 17)
   GUICtrlSetState(-1,$GUI_DISABLE)
   GUICtrlCreateGroup("", -99, -99, 1, 1)
   $x = $x + 5
   $y = $y + 17
   $GroupforCenterCornerforD= GUICtrlCreateGroup("", $x + 10000000000, $y, 185, 265)
   $RadioCentertoCornerforD = GUICtrlCreateRadio("", $x + 50, $y - 25, 17, 17)
   GUICtrlSetState(-1,$GUI_CHECKED)
   GUICtrlSetState(-1,$GUI_DISABLE)
   $LblLine6forD = GUICtrlCreateLabel("center of the map to corner.", $x + 70, $y - 23, 135, 17)
   GUICtrlSetTip(-1, "Choose a direction for your interval of the points that you set")
   GUICtrlSetTip(-1, "Choose a direction for your interval of the points that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $RadioCornertoCenterforD = GUICtrlCreateRadio("", $x + 50, $y - 5, 17, 17)
   GUICtrlSetTip(-1, "Choose a direction for your interval of the points that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $LblLine7forD = GUICtrlCreateLabel("corner to center of the map", $x + 70, $y - 2, 135, 17)
   GUICtrlSetTip(-1, "Choose a direction for your interval of the points that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $x = $x + 15
   $y = $y + 20
   $LblLine8forD = GUICtrlCreateLabel("After each troop, sleep between", $x + 20, $y, 158, 17)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $y = $y + 20
   $InputLinePointLowerSleepforD = GUICtrlCreateInput("50", $x +20, $y - 2, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $LblLine9forD = GUICtrlCreateLabel("-", $x + 65, $y, 5, 20)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $InputLinePointUpperSleepforD = GUICtrlCreateInput("70", $x + 75, $y - 2, 40, 17, $ES_NUMBER)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $LblLine10forD = GUICtrlCreateLabel("ms.", $x + 125, $y , 115, 17)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   $y = $y + 20
   $LblLine11forD = GUICtrlCreateLabel("(1000ms. = 1 sec.)", $x + 20, $y, 115, 17)
   GUICtrlSetTip(-1, "Next troop will wait during your sleep time that you set")
   GUICtrlSetState(-1,$GUI_DISABLE)
   GUICtrlCreateGroup("", -99, -99, 1, 1)
   $x = 455
   $y = 375
   $MultiDropOkforD = GUICtrlCreateButton("OK", $x, $y, 134, 25)
   GUICtrlSetTip(-1, "Click OK button to finish setting. ")
   GUICtrlSetFont(-1, 10, 800, 0, "MS Sans Serif")
   GUICtrlSetColor(-1, 0xFFFFFF)
   GUICtrlSetBkColor(-1, 0x008080)
   GUICtrlSetOnEvent(-1,"OkMultiDropforD")
   $MultiDropCancelforD = GUICtrlCreateButton("CANCEL", $x, $y + 40, 134, 25)
   GUICtrlSetTip(-1, "Click CANCEL button to unset all setting. Your setting date will reset after pressing")
   GUICtrlSetFont(-1, 10, 800, 0, "MS Sans Serif")
   GUICtrlSetColor(-1, 0xFFFF00)
   GUICtrlSetBkColor(-1, 0x800000)
   GUICtrlSetOnEvent(-1,"CancelMultiDropforD")

EndFunc